version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
    default_reviewers:
      - scode
